### ISSUE TITLE
Misdecoded operand in MOVI.n 

### ISSUE THREAD

**Issue by eti1** [yath/ghidra-xtensa#1]
Hello, I'm working on a firmware using a lot of movi.n instructions. 
There is a mistake in the decoding of this instruction, when calculating the sign byte.

You'll find a patch attached.
[xtensa.sinc.patch.txt](https://github.com/yath/ghidra-xtensa/files/3627362/xtensa.sinc.patch.txt)

Thanks for the processor by the way!

**Comment by yath** [comment]
Oops, thanks for the report and the patch!
