### ISSUE TITLE
Pull request ghidra-xtensa to https://github.com/NationalSecurityAgency/ghidra

### ISSUE THREAD

**Issue by bvernoux** [yath/ghidra-xtensa#2]
It will be nice to do a Pull request of this plugin ghidra-xtensa to https://github.com/NationalSecurityAgency/ghidra
Could you add it to https://github.com/NationalSecurityAgency/ghidra/pulls ?

**Comment by yath** [comment]
Opened https://github.com/NationalSecurityAgency/ghidra/pull/1407, thanks for the suggestion!
